# Generated by Django 2.2.2 on 2019-06-11 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('rank', models.CharField(max_length=1)),
                ('role', models.CharField(max_length=24)),
                ('teamsize', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestDeliverables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable', models.BooleanField()),
                ('executive_summary', models.BooleanField()),
                ('personas', models.BooleanField()),
                ('ux_map', models.BooleanField()),
                ('information_architecture', models.BooleanField()),
                ('ux_research', models.BooleanField()),
                ('quest_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questplugger.QuestPin')),
            ],
        ),
    ]
